# @package trainer
_target_: trainRNNbrain.trainer.Trainer_v42.Trainer
max_iter: 600
tol: 1e-10
lr: 0.001
weight_decay: 5e-06
orth_input_only: True
lambda_orth: 0.1
lambda_r: 0.1
lambda_hv: 0.05
lambda_p: 0.01
lambda_h: 0.01
lambda_m: 0.0005
lambda_cv: 0
lambda_z: 0
lambda_d: 0
p: 2
same_batch: True
dropout: True
drop_rate: 0.2

