# @package model
_target_: trainRNNbrain.rnns.RNN_torch.RNN_torch
RNN_tag: ""
activation_name: 'relu'
activation_slope: 1.0
constrained: True
N: 100
dt: 1
tau: 10
exc2inhR: 4.0
connectivity_density_rec: 1.0
spectral_rad: 1.2
sigma_rec: .05
sigma_inp: .05
bias_init_amp: 0.0

