# @package model
_target_: trainRNNbrain.rnns.RNN_torch.RNN_torch
activation_args: {"name": "tanh", "slope": 1.0}
equation_type: "h"
RNN_tag: ""
N: 100
dt: 1
tau: 10
exc_to_inh_ratio: 1
connectivity_density_rec: 1.0
spectral_rad: 1.2
sigma_rec: 0.05
sigma_inp: 0.05
sigma_out: 0.3
bias_range: [0.0, 0.0]