# @package model
_target_: trainRNNbrain.rnns.RNN_torch_spatial.RNN_torch
activation_args: {"name": "relu", "slope": 1.0}
equation_type: "h"
N: 300
dt: 1.0
tau: 10.0
d: 0
exc_to_inh_ratio: 4.0
spectral_rad: 1.2
cdeg: 12
sigma_rec: .05
sigma_inp: .05
sigma_out: .03
bias_range: (0.0, 0.0)






