# @package model
_target_: trainRNNbrain.rnns.RNN_torch.RNN_torch
activation_args: {"name": "softplus", "slope": 1.0, "beta": 5.0}
equation_type: "h"
RNN_tag: ""
N: 100
dt: 1
tau: 10
exc2inhR: 4
connectivity_density_rec: 1.0
spectral_rad: 1.2
sigma_rec: .05
sigma_inp: .05
sigma_out: .03
bias_range: [0.0, 0.0]




