# @package model
_target_: trainRNNbrain.rnns.RNN_torch.RNN_torch
activation_args: {"name": "sigmoid", "slope": 7.5}
RNN_tag: ""
N: 100
dt: 1
tau: 10
exc2inhR: 4
connectivity_density_rec: 1.0
spectral_rad: 1.2
sigma_rec: .05
sigma_inp: .05
bias_init_amp: 0.0




