# @package model
_target_: trainRNNbrain.rnns.RNN_torch.RNN_torch
RNN_tag: ""
activation_args: {"name": "relu", "slope": 1.0}
equation_type: "h"
N: 100
dt: 1
tau: 10
exc2inhR: 4.0
gamma: 0.1
connectivity_density_rec: 1.0
spectral_rad: 1.2
sigma_rec: .05
sigma_inp: .05
sigma_out: .03
bias_range: (0.0, 0.0)

