# @package task
taskname: "CDDM"
_target_: trainRNNbrain.tasks.TaskCDDM.TaskCDDM
T: 300
seed: null
T_cue_on: 0
T_cue_off: 300
T_stim_on: 100
T_stim_off: 300
T_dec_on: 200
T_dec_off: 300
n_inputs: 6
n_outputs: 2
mask_params:
  - (0, 100)
  - (200, 300)
coherences: [-1.0, -0.5, -0.25, -0.125, -0.0625, -0.03125, -0.015625,
             0.0,
             0.015625, 0.03125, 0.0625, 0.125, 0.25, 0.5, 1.0]
task_params: ["n_steps",
              "n_inputs", "n_outputs",
              "cue_on", "cue_off", "stim_on", "stim_off", "dec_on", "dec_off",
              "coherences"]