# @package task
taskname: "MemoryAntiAngle"
_target_: trainRNNbrain.tasks.TaskMemoryAntiAngle.TaskMemoryAntiAngle
T: 120
seed: null
T_stim_on: 10
T_stim_off: 20
T_recall_on: 90
T_recall_off: 120
T_random_window: 10
n_inputs: 5
n_outputs: 3
mask_params:
  - (0, 90)
  - (100, 120)
task_params: ["n_steps",
              "n_inputs", "n_outputs",
              "stim_on", "stim_off", "recall_on", "recall_off",
              "random_window"]